yml  update

diff --git a/.github/workflows/laravel.yml b/.github/workflows/laravel.yml
--- a/.github/workflows/laravel.yml
+++ b/.github/workflows/laravel.yml
@@ -26,8 +26,17 @@ jobs:
         run: composer install --no-progress --no-suggest
       - name: Update Composer dependencies
         run: composer update --no-progress --no-suggest
-      - name: Change directory to Laravel project
-        run: cd Laravel
+      - name: Find Laravel project directory
+        run: |
+          ls -la
+          if [[ -d "Laravel" ]]; then
+            cd Laravel
+          elif [[ -d "laravel" ]]; then
+            cd laravel
+          else
+            echo "Unable to find Laravel project directory"
+            exit 1
+          fi
       - name: Run database seeder
         run: php artisan db:seed
       - name: Pull latest changes
